name: yamltools
description: Some tools for making your yaml life easier.
version: 1.0.0
repository: https://github.com/fischerscode/dart-yamlTools

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ">=3.0.0 <4.0.0"

dev_dependencies:
  pedantic: ^1.9.0
